//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicLayerSample2_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphicLayerSample2_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra sign here.
        /// </summary>
        public static string AddExtraSignatureMenuItem {
            get {
                return ResourceManager.GetString("AddExtraSignatureMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stamp.
        /// </summary>
        public static string AddStamp {
            get {
                return ResourceManager.GetString("AddStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add text.
        /// </summary>
        public static string AddTextLayerMenuItem {
            get {
                return ResourceManager.GetString("AddTextLayerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit the element.
        /// </summary>
        public static string CannotEditElement {
            get {
                return ResourceManager.GetString("CannotEditElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный XML.
        /// </summary>
        public static string CannotParseXml {
            get {
                return ResourceManager.GetString("CannotParseXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Graphic layer element.
        /// </summary>
        public static string EditGraphicLayerElementTitle {
            get {
                return ResourceManager.GetString("EditGraphicLayerElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select offsets, mm.
        /// </summary>
        public static string ImageOffsets {
            get {
                return ResourceManager.GetString("ImageOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned signature file.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking to page corner.
        /// </summary>
        public static string LinkToCorner {
            get {
                return ResourceManager.GetString("LinkToCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move signature here.
        /// </summary>
        public static string MoveSignatureMenuItem {
            get {
                return ResourceManager.GetString("MoveSignatureMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        public static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;image path&gt;.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move signature here and rotate.
        /// </summary>
        public static string RotateSignatureMenuItem {
            get {
                return ResourceManager.GetString("RotateSignatureMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file types: *.jpg; *.jpeg; *.png.
        /// </summary>
        public static string SupportedFiles {
            get {
                return ResourceManager.GetString("SupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic layer settings.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string txtFontSize {
            get {
                return ResourceManager.GetString("txtFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text here:.
        /// </summary>
        public static string txtInputText {
            get {
                return ResourceManager.GetString("txtInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic layer settings.
        /// </summary>
        public static string txtMenuItem {
            get {
                return ResourceManager.GetString("txtMenuItem", resourceCulture);
            }
        }
    }
}
